# Generated by Django 4.2.7 on 2024-03-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_userprofile_userregister_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='password2',
        ),
    ]
