# Generated by Django 4.2.7 on 2024-04-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_password1_userregister_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
