# Generated by Django 4.2.7 on 2024-04-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
