# Generated by Django 4.2.7 on 2023-11-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
