# Generated by Django 4.2.7 on 2023-11-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
