# Generated by Django 4.2.7 on 2024-03-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
