# Generated by Django 4.2.7 on 2024-03-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_productproxy_alter_category_options_and_more'),
    ]

    operations = [

    ]
