# Generated by Django 4.2.7 on 2024-05-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductProxy',
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Характеристика товару', 'verbose_name_plural': 'Характеристики товарів'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'Значення характеристики товару', 'verbose_name_plural': 'Значення характеристик товарів'},
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='market.productattribute'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
