# Generated by Django 4.2.7 on 2024-07-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_delete_productproxy_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/%d', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Опис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банери',
                'ordering': ['order'],
            },
        ),
    ]
