# Generated by Django 4.2.7 on 2024-07-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='alt',
            field=models.CharField(default=1, max_length=200, verbose_name='Альтернативний текст'),
            preserve_default=False,
        ),
    ]
