# Generated by Django 4.2.7 on 2024-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_rename_banner_homeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
