# Generated by Django 4.2.7 on 2024-07-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_homeimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimage',
            name='url',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='URL'),
        ),
    ]
