# Generated by Django 4.2.7 on 2024-07-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
