# Generated by Django 4.2.7 on 2024-08-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Мета опис'),
        ),
    ]
