# Generated by Django 4.2.7 on 2024-05-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
