# Generated by Django 4.2.7 on 2024-05-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_price',
        ),
    ]
