# Generated by Django 4.2.7 on 2024-04-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_cardnumber_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cardNumber',
            new_name='transactionNumber',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Опрацювання', 'Опрацювання'), ('Комплектація', 'Комплектація'), ('Доставляється', 'Доставляється'), ('Отримано покупцем', 'Отримано покупцем'), ('Відмінено', 'Відмінено')], default='Опрацювання', max_length=20),
        ),
    ]
