# Generated by Django 4.2.7 on 2024-05-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_payment_remove_order_transactionnumber_order_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Кредитна карта'), ('cash', 'Готівка')], max_length=10),
        ),
    ]
