# Generated by Django 4.2.7 on 2024-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Кредитна карта'), ('cash', 'Готівка')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
